using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Content;
using Microsoft.Xna.Framework.Graphics;
using Microsoft.Xna.Framework.Input;
using MonoEditorEndless.Engine.StateManager;
using MonoEditorEndless.Engine.UI;
using System;
using System.Diagnostics;
using static System.Windows.Forms.VisualStyles.VisualStyleElement.TrayNotify;

namespace MonoEditorEndless.Game
{
    internal class StateMenuMaker : State
    {
        private Texture2D _background;
        private Texture2D _panel;
        private string _title;
        private ButtonList _buttonList;
        private SpriteFont _font;
        float scale = 1f;

        ContentManager Content;



        // Events generated by clicking buttons
        public event EventHandler GameStart;
        public event EventHandler HighScores;
        public event EventHandler Controls;
        public event EventHandler ExitGame;
        public StateMenuMaker(ContentManager content, GraphicsDevice graphicsDevice)
        {
            Name = "menu-maker";
            Content = content;
        }
        public override void Enter(object owner)
        {
            _font = Content.Load<SpriteFont>("Content/Fonts/File");
            _background = Content.Load<Texture2D>("Content/Textures/bg");
            // Initialize the button list with button indicator and padding between buttons
            _buttonList = new ButtonList(null, 10, 10, _font, 50);
            LoadMainButtons();
        }
        public override void Execute(object owner, GameTime gameTime)
        {
            Debug.WriteLine(Mouse.GetState().ScrollWheelValue);
            float step = 0.002f;
            float minScroll = 1 / (4 * step);
            int mouseWheelValue = Mouse.GetState().ScrollWheelValue;
            if (mouseWheelValue >= minScroll)
            {
                scale = (float)Mouse.GetState().ScrollWheelValue * step;
            }
            else
            {
                scale = minScroll * step;
            }
            _buttonList.Update();
        }
        public override void Exit(object owner) { _buttonList.Clear(); }
        public override void Draw(GraphicsDevice graphicsDevice = null, SpriteBatch spriteBatch = null)
        {

            Matrix transform = Matrix.CreateScale(scale);
            transform *= Matrix.CreateTranslation(
                graphicsDevice.Viewport.Width / 2 - graphicsDevice.Viewport.Width * scale / 2,
                graphicsDevice.Viewport.Height / 2 - graphicsDevice.Viewport.Height * scale / 2,
                0);
            spriteBatch.Begin(SpriteSortMode.Deferred, null, null, null, null, null, transform);
            spriteBatch.Draw(_background,
                new Rectangle(0, 0, graphicsDevice.Viewport.Width, graphicsDevice.Viewport.Height),
                Color.White);
            _buttonList.Draw(spriteBatch);
            spriteBatch.End();
            //base.Draw(owner, GraphicsDevice, spriteBatch);
        }
        private void LoadMainButtons()
        {
            _buttonList.AddButton("Start");
            _buttonList.AddButton("High Scores");
            _buttonList.AddButton("Controls");
            _buttonList.AddButton("Exit");
            // Handle button selection
            _buttonList.ButtonClicked += this.HandleButtonSelection;
            // Play sound on button switch
            //_buttonList.ButtonSwitched += (object sender, EventArgs e) => { switchSound.Play(); };
        }
        private void HandleButtonSelection(object sender, Button button)
        {
            // Handle the button selection based on the name of the button
            switch (button.GetText())
            {
                case "Start":
                    GameStart(this, EventArgs.Empty);
                    break;
                case "High Scores":
                    HighScores(this, EventArgs.Empty);
                    break;
                case "Controls":
                    Controls(this, EventArgs.Empty);
                    break;
                case "Exit":
                    ExitGame(this, EventArgs.Empty);
                    break;
                default:
                    break;
            }
            // Play the sound effect related to the select button
            //selectSound.Play();
        }
    }
}
